name: Playwright Demo Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Check out repository
    - uses: actions/setup-node@v4
      name: Set up Node.js
      with:
        node-version: '20'  # Nodejs version
        cache: 'npm'        # Use cache to increase efficiency
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test # run all tests
    - name: Upload Playwright report
      if: always()  # save report even when tests failed
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30